### ISSUE TITLE
Doesn't find processing-server

### ISSUE THREAD

**Issue by boredland** [DIYBookScanner/spreadpi#31]
Hi there,

I've got a processing-server at an adress running, acessible through my webbrowser. And a spreadpi, accessible through webinterface, too. Sadly the spreadpi doesn't find any running processing-server. Are there any ports, besides 5000, that a regularly used for the processing-server that perhaps aren't open?
Info: my server runs in a chroot in my local network. webinterface is accessible from all devices in my network.

**Comment by jbaiter** [comment]
The auto-discovery is a bit brittle, does it work if you enter the IP and port of your postprocessing server manually?
Also, sorry for being so quiet/inactive at the moment, I'm pretty busy with university at the moment and am currently unable to devote much time to open source development :/

**Comment by boredland** [comment]
Jep, manual IP does work. That's allright for me, but for user expirience thats not for the best, I think.

**Comment by boredland** [comment]
I'll close that for now.

**Comment by jbaiter** [comment]
Yes, it's not ideal, but short of adding a ton of extra dependencies and complexity (zeroconf, bonjour, mdns, etc) UDP broadcasting seemed to be the 'easiest' way to go about it at the time I researched that topic (service autodiscovery).
You're welcome to bring in alternative implementations, though!
